---
bind_acls:
  - name: trusted
    match_list:
      - 127.0.0.1
      - 10.0.0.0/24
bind_allow_query:
  - trusted
bind_forwarders:
  - 10.10.20.11
  - 10.10.20.12
  - 10.10.20.13
bind_listen_ipv4:
  - 127.0.0.1
  - 10.0.0.101
bind_recursion: true
bind_zone_domains:
  - name: hci.pve
    networks:
      - '10.0.0'
    name_servers:
      - ns1.hci.pve.
      - ns2.hci.pve.
    hostmaster_email: admin
    hosts:
      - name: ns1
        ip: 10.0.0.101
      - name: ns2
        ip: 10.0.0.102
      - name: gateway1
        ip: 10.0.0.101
      - name: gateway2
        ip: 10.0.0.102
      - name: kube-cluster1
        ip: 10.0.0.110
      - name: kube-master1
        ip: 10.0.0.111
      - name: kube-master2
        ip: 10.0.0.112
      - name: kube-master3
        ip: 10.0.0.113
      - name: kube-worker1
        ip: 10.0.0.121
      - name: kube-worker2
        ip: 10.0.0.122
      - name: kube-worker3
        ip: 10.0.0.123
bind_zone_master_server_ip: 10.0.0.101
