---
- hosts: localhost
  tasks:
    - name: "add custom homebrew repos"
      community.general.homebrew_tap:
        name:
          [
            adoptopenjdk/openjdk,
            fishtown-analytics/dbt,
            heroku/brew,
            homebrew/cask-versions,
            thoughtbot/formulae,
            weaveworks/tap,
            jeffreywildman/homebrew-virt-manager
          ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - android-sdk
        - docker
        - google-chrome
        - microsoft-edge
        - microsoft-remote-desktop
        - obsidian
        - iterm2
        - telegram-desktop
        - visual-studio-code
        - vlc
        - zoom
        - xquartz
        - double-commander
        - scroll-reverser
        - lazygit
