---
- hosts: localhost
  tasks:
    - name: "Install homebrew packages"
      community.general.homebrew:
        name:
          [
            "autoconf",
            "automake",
            "bfg",
            "coreutils",
            "curl",
            "wget",
            "direnv",
            "dnsmasq",
            "asdf",
            "fzf",
            "gnu-time",
            "gpg",
            "htop",
            "gtop",
            "fd",
            "miller",
            "exa",
            "asciinema",
            "chezmoi",
            "lnav",
            "magic-wormhole",
            "ffsend",
            "up",
            "navi",
            "kubectx",
            "kubernetes-cli",
            "kubernetes-helm",
            "libtool",
            "libxslt",
            "libyaml",
            "mas",
            "openssl",
            "gradle",
            "libssh2",
            "pkg-config",
            "postgresql",
            "rcm",
            "readline",
            "sqlite3",
            "tmux",
            "unixodbc",
            "unzip",
            "vim",
            "watchman",
            "xz",
            "yarn",
            "zlib",
            "zsh",
            "zplug",
            "tig",
            "adr-tools",
            "virt-viewer",
            "telnet",
            "most",
            "bpytop",
            "jq",
            "yq",
            "gtop",
            "tldr",
            "fx",
          ]
        state: present
        update_homebrew: yes

    - name: "Modern Unix tools"
      shell: brew install curlie httpie procs cheat dog mcfly ripgrep fd broot duf dust delta exa bat zoxide ripgrep gping glances lazygit

    - name: "IaC sake"
      shell: |
             brew tap alajmo/sake
             brew install sake

    - name: "pretty ping"
      shell: |
             wget https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping
             chmod +x prettyping
             mv prettyping ~/bin/

    - name: "Android tools"
      shell: brew install jadx

    - name: "nvm"
      shell: |
            brew install nvm
            mkdir ~/.nvm
