---
playprj:
  hosts:
    node1:
      ansible_host: node1.ts.cinds.io
    node2:
      ansible_host: node2.ts.cinds.io
    node3:
      ansible_host: node3.ts.cinds.io
    node4:
      ansible_host: node4.ts.cinds.io
