---
- name: Install docker cli
  hosts: proxmox
  gather_facts: yes
  tasks:
  - name: add GPG key
    shell: |
      mkdir -p /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
  - name: Install docker
    ansible.builtin.apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      state: latest
      fail_on_autoremove: yes
