- name: "Create fix network IP"
  copy:
    dest: /etc/netplan/99fixIP.yaml
    content: |
      # This file describes the network interfaces available on your system
      # For more information, see netplan(5).
      network:
        version: 2
        renderer: networkd
        ethernets:
          eno0:
            match:
              name: en*
            dhcp4: false
            dhcp6: false
        bridges:
          br0:
            dhcp4: true
            dhcp6: true
            interfaces:
            - eno0
            addresses:
            - {{fix_ip_address}}
  register: result
  when: fix_ip_address | default(False)

- name: refresh netplan
  shell: "netplan apply"
  when: result.changed
