---
- name: Update and Upgrade Homebrew
  hosts: all
  environment:
    PATH: /home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}
  gather_facts: yes
  become_user: sungyong
  tasks:
  - name: Upgrade All package
    homebrew:
      update_homebrew: yes
      upgrade_all: yes

